### ISSUE TITLE
FileNotFoundError when running fill_data.sh

### ISSUE THREAD

**Issue by kirnap** [samarthbhargav/tomt-data#4]
Hi,

After I follow the instructions in readme, and run `sh fill_data.sh` I got the following error:

```
[2023-01-30 16:09:26,946] INFO [__main__.<module>:56] args: Namespace(cache='./.submissions_cache', force_refresh=True, input='./dataset/Books/raw_queries.json', out='./dataset/Books/queries.json', reddit_config_path='./reddit_config.json')
Traceback (most recent call last):
  File "process_dataset.py", line 61, in <module>
    load_fields(data, args.cache, args.reddit_config_path, args.force_refresh)
  File "process_dataset.py", line 27, in load_fields
    reddit_config = utils.read_json(reddit_config_path)
  File "/Users/omerkirnap/Documents/Developer/tomt-data/tomt/data/utils.py", line 50, in read_json
    with open(path, "r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: './reddit_config.json'
```

Do I need to provide reddit config, if so how?

**Comment by samarthbhargav** [comment]
This is a file with "client_id", and "client_secret" as such:

```
{
    "client_id": "CLIENT ID",
    "client_secret": "CLIENT SECRET"
}
```

For getting these, [first create an application](https://github.com/reddit-archive/reddit/wiki/OAuth2), using the 'script' option (you can use`http://localhost:8080` for redirect URI). Then, copy over the secret (this is the field labelled "secret") and client id (at the top, just below "personal use script") into a file like above and save it as `reddit_config.json`. Hope that clears it up!

**Comment by kirnap** [comment]
Yes, it worked! Thank you so much for the detailed and quick response!

As far as I understand, that's all I need in order to obtain dataset proposed in the paper, right?

**Comment by samarthbhargav** [comment]
You're welcome :) 
Yes, once you run the shell script, you should have the data.
